version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    command:
      - --api=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - source: \\./pipe/docker_engine
        target: \\./pipe/docker_engine
        type: npipe
    restart: unless-stopped
